name: collector
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  package_info_plus: ^1.4.0
  url_launcher: ^6.0.20
  path_provider: ^2.0.9
  auto_size_text: ^3.0.0
  camera: ^0.9.4+14
  permission_handler: ^9.2.0
  page_transition: ^2.0.5
  font_awesome_flutter: ^10.0.0
  geolocator: ^8.2.0
  flutter_compass: ^0.7.0
  shared_preferences: ^2.0.13
  uuid: ^3.0.6
  flutter_sms: ^2.3.2
  photo_view: ^0.13.0
  intl: ^0.17.0
  share_plus: ^4.0.3

dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
